  
---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=/root{{ token_file }} dest=/home/join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /home/join_token | tail -2 > out.sh
     sh out.sh